import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import ReduxProvider from "@providers/redux-provider";
import { WalletContextProvider } from "@/providers/WalletContextProvider";
import "./globals.css";
import Image from "next/image";
import glow_left from "@public/images/glow_left.png";
import glow_bottom from "@public/images/glow_bottom.png";
import glow_top from "@public/images/glow_top.png";

const urbanist = Urbanist({
  variable: "--font-urbanist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Video Token",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${urbanist.variable} min-w-full bg-[#161622]`}>
        <ReduxProvider>
          <WalletContextProvider>{children}</WalletContextProvider>
        </ReduxProvider>

        <div className="fixed inset-0 pointer-events-none">
          <Image
            src={glow_left}
            fill
            fetchPriority="high"
            alt="glow_right"
            className="h-full w-full object-contain object-left-bottom"
            priority
          />
          <Image
            src={glow_top}
            fill
            fetchPriority="high"
            alt="glow_right"
            className="h-full w-full object-contain object-right-top"
            priority
          />
          <Image
            src={glow_bottom}
            fill
            fetchPriority="high"
            alt="glow_right"
            className="h-full w-full object-contain object-right-bottom"
            priority
          />
        </div>
      </body>
    </html>
  );
}
